---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeapp-pv-volume
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kubeapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeapp-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-nginxphpfpm
  labels:
    app: kubeapp-nginxphpfpm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeapp-nginxphpfpm
  template:
    metadata:
      labels:
        app: kubeapp-nginxphpfpm
    spec:
      volumes:
        - name: kubeapp-nginxphpfpm-storage
          persistentVolumeClaim:
            claimName: kubeapp-pv-claim
      imagePullSecrets:
        - name: regcred
        - name: registry-crt
      containers:
        - name: kubeapp-nginxphpfpm
          image: panzdb1.world:443/nginx-phpfpm:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: kubeapp-nginxphpfpm-storage
              mountPath: /use/share/nginx/html/
---
apiVersion: v1
kind: Service
metadata:
  name: kubeapp-nginxphpfpm-service
spec:
  type: LoadBalancer
  selector:
    app: kubeapp-nginxphpfpm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80