---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeapp-pv-volume
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kubeapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeapp-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
